OCPRHV-596: Port to go-ovirt-client
openshift/ovirt-csi-driver pull request #88
Opened 2021-10-12 08:08 UTC by Gal-Zaidman

This PR ports the oVirt CSI driver to use the go-ovirt-client instead of the go-ovirt golang sdk.
This change will help up remove code duplication and increase readability of the driver

2021-10-12 09:19 UTC, janosdebugs requested changes
A few minor things. The most important one would be using the `Client` instead of the `ClientWithLegacy...` interface to enable testing/mocking later.

2021-10-12 09:19 UTC, janosdebugs commented on pkg/service/driver.go
> +func NewOvirtCSIDriver(ovirtClient ovirtclient.ClientWithLegacySupport, client client.Client, nodeId string) *OvirtCSIDriver {
We should return the `Client` interface if possible, let's not give us / other people an out to fall back to the old SDK. This interface will also make it impossible to add mocks as the mock client only implements `Client`.

2021-10-12 09:19 UTC, janosdebugs commented on internal/ovirt/ovirt.go
> +const defaultOvirtConfigEnvVar = "OVIRT_CONFIG"
This should go in the client.

2021-10-12 09:19 UTC, janosdebugs commented on internal/ovirt/ovirt.go
>  type Config struct {
This struct should go in the client.

2021-10-12 09:19 UTC, janosdebugs commented on pkg/service/controller.go
> +		msg := fmt.Errorf("error while finding disk %s, error %w", volumeID, err)
This will be a duplicate error message, the GetDisk will already return an error message with the disk ID included.

2021-10-12 09:19 UTC, janosdebugs commented on pkg/service/identity.go
> +	ovirtClient ovirtclient.ClientWithLegacySupport
Please use the `Client` interface to enable later mocking.

2021-10-13 06:45 UTC, Gal-Zaidman commented on pkg/service/helper.go
>  func waitForDiskStatusOk(ctx context.Context, conn *ovirtsdk.Connection, diskID string) error {
removed :)

2021-10-19 06:00 UTC, ghost approved these changes
/lgtm

2021-10-19 06:00 UTC, janosdebugs commented
/lgtm

2021-10-19 06:01 UTC, merged